---
- name: Ping VMs from ManageIQ for Health Check
  hosts: localhost  # Use localhost for interacting with ManageIQ
  gather_facts: no

  tasks:
    - name: Get the list of running VMs from ManageIQ
      manageiq_vmdb:
        href: "/vms"
        query:
          - state: "on"  # Only include VMs that are running
      register: running_vms

    - name: Ping each VM to check if it is up
      ping:
        host: "{{ item.ipaddresses[0] }}"  # Assuming 'ipaddresses' is a field in VM object
      loop: "{{ running_vms.resources }}"
      register: ping_result
      ignore_errors: yes  # Ignore errors if ping fails

    - name: Report Ping Result
      debug:
        msg: "VM {{ item.name }} is reachable: {{ ping_result.results[loop.index0].ping }}"
      when: ping_result is defined and ping_result.results[loop.index0].ping is defined
      loop: "{{ running_vms.resources }}"
